-- CITIES table creation
CREATE TABLE CITIES (
    CITY CHAR(20) PRIMARY KEY,
    STATE CHAR(20)
);

-- WAREHOUSES table creation
CREATE TABLE WAREHOUSES (
    WID INTEGER PRIMARY KEY,
    WNAME CHAR(30),
    LOCATION CHAR(20) REFERENCES CITIES(CITY),
    EXTRA json
);

-- STORES table creation
CREATE TABLE STORES (
    SID INTEGER PRIMARY KEY,
    STORE_NAME CHAR(20),
    LOCATION_CITY CHAR(20) REFERENCES WAREHOUSES(LOCATION)
);

-- CUSTOMER table creation
CREATE TABLE CUSTOMER (
    CNO INTEGER PRIMARY KEY,
    CNAME CHAR(50),
    ADDR VARCHAR(50),
    CU_CITY CHAR(20) REFERENCES CITIES(CITY)
);

-- ORDERS table creation
CREATE TABLE ORDERS (
    ONO INT PRIMARY KEY,
    ODATE DATE,
    CUSTOMER_ID INTEGER REFERENCES CUSTOMER(CNO)
);

-- ITEMS table creation
CREATE TABLE ITEMS (
    ITEMNO INTEGER PRIMARY KEY,
    DESCRIPTION TEXT,
    WEIGHT DECIMAL(5,2),
    COST DECIMAL(5,2)
);

-- ORDERED_ITEMS table creation (Bridge Table for Items-Orders M:M)
CREATE TABLE ORDERED_ITEMS (
    ORDER_ID INTEGER REFERENCES ORDERS(ONO),
    ITEM_ID INTEGER REFERENCES ITEMS(ITEMNO),
    ordered_quantity INTEGER,
    PRIMARY KEY (ORDER_ID, ITEM_ID)
);

-- STORE_ITEMS table creation (Bridge Table for Stores-Items M:M)
CREATE TABLE STORE_ITEMS (
    STORE_ID INTEGER REFERENCES STORES(SID),
    ITEM_ID INTEGER REFERENCES ITEMS(ITEMNO),
    quantity INTEGER,
    PRIMARY KEY (STORE_ID, ITEM_ID)
);
